name = "global-durable-objects-fetch-urls"
main = "index.js"
compatibility_date = "2024-05-01"
workers_dev = true

# Replace with your actual Cloudflare account ID
account_id = "f9e6c318356fc5438de52004c85a0d5b"

[durable_objects]
bindings = [
  { name = "GlobalDurableObjectsFetchUrls", class_name = "GlobalDurableObjectsFetchUrls" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GlobalDurableObjectsFetchUrls"]

[[d1_databases]]
binding = "DB"
database_name = "yoast_sitemaps"
database_id = "a315633c-fe60-4a5b-8a1f-a2f1a2d76945"
