name = "global-durable-objects-fetch-urls"
main = "index.js"
compatibility_date = "2024-05-01"
workers_dev = true

account_id = "YOUR_CLOUDFLARE_ACCOUNT_ID"

[durable_objects]
bindings = [
  { name = "GLOBAL_FETCH_URLS", class_name = "GlobalFetchUrls" }
]

[[migrations]]
tag = "v1"
new_classes = ["GlobalFetchUrls"]

[[d1_databases]]
binding = "DB"
database_name = "global_fetch_urls_db"
database_id = "a315633c-fe60-4a5b-8a1f-a2f1a2d76945"
